//! The generated workspace's `Cargo.lock`.
//!
//! Every generated Rust service has the same closed dependency set (axum,
//! serde, serde_json, tokio — see `rust_service`), so one canonical lock —
//! captured once from a generated system and vendored under `assets/` —
//! is valid for every generated workspace. Emitting it makes `generate`
//! deterministic all the way down to dependency versions, and it is what
//! lets the root flake build services purely (`cargoLock.lockFile`).
//!
//! The asset holds only the registry entries; the workspace-member entries
//! are appended here per spec, merged in cargo's sorted order so the file is
//! byte-identical to what cargo itself would write.

use metaarch_spec::{Lang, SystemSpec};

use crate::Artifact;

/// Registry entries of the canonical dependency graph, alphabetized, without
/// the workspace members. Regenerate by running `cargo build` in a generated
/// system and stripping the member entries from its `Cargo.lock`.
const BASE: &str = include_str!("../assets/base.cargo.lock");

pub(crate) fn cargo_lock(spec: &SystemSpec) -> Artifact {
    let mut blocks: Vec<(String, String)> = BASE
        .split("[[package]]\n")
        .filter(|block| !block.trim().is_empty())
        .map(|block| {
            let name = block
                .lines()
                .find_map(|line| line.strip_prefix("name = \""))
                .expect("base lock entry has a name")
                .trim_end_matches('"')
                .to_string();
            (name, format!("[[package]]\n{}", block.trim_end()))
        })
        .collect();
    for service in spec.services.iter().filter(|s| s.lang == Some(Lang::Rust)) {
        blocks.push((
            service.name.clone(),
            format!(
                "[[package]]\nname = \"{}\"\nversion = \"0.1.0\"\ndependencies = [\n \"axum\",\n \"serde\",\n \"serde_json\",\n \"tokio\",\n]",
                service.name
            ),
        ));
    }
    // Cargo keeps entries sorted by name; all names here are unique.
    blocks.sort_by(|a, b| a.0.cmp(&b.0));
    let body = blocks
        .into_iter()
        .map(|(_, block)| block)
        .collect::<Vec<_>>()
        .join("\n\n");
    Artifact::file(
        "Cargo.lock",
        format!(
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n{body}\n"
        ),
    )
}
