//! CLI: `metaarch-expand expand <file.quilt>…` writes each file's expanded
//! sibling (the stem, `.quilt` stripped); `parse <file.quilt>…` parses and
//! reports without writing — the mode for `.arch.quilt` files until arch
//! grows a `MetaLanguage` (phase 4c).

use std::path::PathBuf;
use std::process::ExitCode;

use clap::{Parser, Subcommand};
use metaarch_expand::{arch_multi, parse_stem};
use quilt::prelude::{miette, write, Result, STerm, NL};

#[derive(Parser)]
#[command(
    name = "metaarch-expand",
    about = "quilt expander with `arch` registered as a dynamic language"
)]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Expand each .quilt file to its generated sibling.
    Expand { files: Vec<PathBuf> },
    /// Parse each .quilt file (report the root + round-trip) without writing.
    Parse { files: Vec<PathBuf> },
}

fn stem_of(file: &PathBuf) -> Result<(String, PathBuf)> {
    let name = file
        .file_name()
        .and_then(|n| n.to_str())
        .ok_or_else(|| miette!("invalid filename: {}", file.display()))?;
    let stem = name
        .strip_suffix(".quilt")
        .ok_or_else(|| miette!("{}: expected a .quilt file", file.display()))?;
    Ok((stem.to_string(), file.with_file_name(stem)))
}

fn expand_file(file: &PathBuf) -> Result<()> {
    let (stem, out) = stem_of(file)?;
    let input = std::fs::read_to_string(file)
        .map_err(|e| miette!("failed to read {}: {e}", file.display()))?;
    let mut multi = arch_multi();
    let (chain, term) = parse_stem(&mut multi, &stem, &input)?;
    if chain[0] == metaarch_lang::LANG {
        return Err(miette!(
            "{}: arch is parse-only until it grows a MetaLanguage (phase 4c) — use `parse`",
            file.display()
        ));
    }
    let expanded = multi.expand_lang(chain[0], &term)?;
    let header = "//! DO NOT EDIT. GENERATED BY `metaarch-expand`.";
    expanded.dump_with_cmds(
        out.to_str()
            .ok_or_else(|| miette!("invalid output path: {}", out.display()))?,
        &[write(header), NL, NL],
        &[],
    )?;
    println!("expanded {} -> {}", file.display(), out.display());
    Ok(())
}

fn parse_file(file: &PathBuf) -> Result<()> {
    let (stem, _) = stem_of(file)?;
    let input = std::fs::read_to_string(file)
        .map_err(|e| miette!("failed to read {}: {e}", file.display()))?;
    let mut multi = arch_multi();
    let (chain, term) = parse_stem(&mut multi, &stem, &input)?;
    let round_trip = if term.coparse() == input {
        "round-trips exactly"
    } else {
        "coparse differs from source"
    };
    println!(
        "parsed {} (chain {:?}) — {}",
        file.display(),
        chain,
        round_trip
    );
    Ok(())
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    let (files, run): (&Vec<PathBuf>, fn(&PathBuf) -> Result<()>) = match &cli.cmd {
        Cmd::Expand { files } => (files, expand_file),
        Cmd::Parse { files } => (files, parse_file),
    };
    let mut failed = false;
    for file in files {
        if let Err(e) = run(file) {
            eprintln!("{e:?}");
            failed = true;
        }
    }
    if failed {
        ExitCode::FAILURE
    } else {
        ExitCode::SUCCESS
    }
}
