[package]
name = "metaarch"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
metaarch-codegen.workspace = true
metaarch-expand = {path = "../metaarch-expand"}
metaarch-parser.workspace = true
metaarch-spec.workspace = true
