/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_system = 2,
  anon_sym_service = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_lang = 6,
  anon_sym_port = 7,
  anon_sym_db = 8,
  anon_sym_table = 9,
  anon_sym_COMMA = 10,
  anon_sym_COLON = 11,
  sym_pk = 12,
  anon_sym_enum = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_emits = 16,
  anon_sym_consumes = 17,
  anon_sym_impl = 18,
  anon_sym_u2196 = 19,
  anon_sym_u2197 = 20,
  sym_fragment_text = 21,
  sym_path = 22,
  sym_number = 23,
  sym_comment = 24,
  sym_source_file = 25,
  sym_system = 26,
  sym_service = 27,
  sym__entry = 28,
  sym_lang_entry = 29,
  sym_port_entry = 30,
  sym_db_entry = 31,
  sym_table = 32,
  sym_field = 33,
  sym__type = 34,
  sym_type_name = 35,
  sym_enum_type = 36,
  sym_emits_entry = 37,
  sym_consumes_entry = 38,
  sym_impl_entry = 39,
  sym_method = 40,
  sym_fragment_language = 41,
  sym_fragment = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_service_repeat1 = 44,
  aux_sym_db_entry_repeat1 = 45,
  aux_sym_table_repeat1 = 46,
  aux_sym_enum_type_repeat1 = 47,
  aux_sym_fragment_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_system] = "system",
  [anon_sym_service] = "service",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_lang] = "lang",
  [anon_sym_port] = "port",
  [anon_sym_db] = "db",
  [anon_sym_table] = "table",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [sym_pk] = "pk",
  [anon_sym_enum] = "enum",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_emits] = "emits",
  [anon_sym_consumes] = "consumes",
  [anon_sym_impl] = "impl",
  [anon_sym_u2196] = "\u2196",
  [anon_sym_u2197] = "\u2197",
  [sym_fragment_text] = "fragment_text",
  [sym_path] = "path",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_system] = "system",
  [sym_service] = "service",
  [sym__entry] = "_entry",
  [sym_lang_entry] = "lang_entry",
  [sym_port_entry] = "port_entry",
  [sym_db_entry] = "db_entry",
  [sym_table] = "table",
  [sym_field] = "field",
  [sym__type] = "_type",
  [sym_type_name] = "type_name",
  [sym_enum_type] = "enum_type",
  [sym_emits_entry] = "emits_entry",
  [sym_consumes_entry] = "consumes_entry",
  [sym_impl_entry] = "impl_entry",
  [sym_method] = "method",
  [sym_fragment_language] = "fragment_language",
  [sym_fragment] = "fragment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_service_repeat1] = "service_repeat1",
  [aux_sym_db_entry_repeat1] = "db_entry_repeat1",
  [aux_sym_table_repeat1] = "table_repeat1",
  [aux_sym_enum_type_repeat1] = "enum_type_repeat1",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_system] = anon_sym_system,
  [anon_sym_service] = anon_sym_service,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_lang] = anon_sym_lang,
  [anon_sym_port] = anon_sym_port,
  [anon_sym_db] = anon_sym_db,
  [anon_sym_table] = anon_sym_table,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_pk] = sym_pk,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_emits] = anon_sym_emits,
  [anon_sym_consumes] = anon_sym_consumes,
  [anon_sym_impl] = anon_sym_impl,
  [anon_sym_u2196] = anon_sym_u2196,
  [anon_sym_u2197] = anon_sym_u2197,
  [sym_fragment_text] = sym_fragment_text,
  [sym_path] = sym_path,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_system] = sym_system,
  [sym_service] = sym_service,
  [sym__entry] = sym__entry,
  [sym_lang_entry] = sym_lang_entry,
  [sym_port_entry] = sym_port_entry,
  [sym_db_entry] = sym_db_entry,
  [sym_table] = sym_table,
  [sym_field] = sym_field,
  [sym__type] = sym__type,
  [sym_type_name] = sym_type_name,
  [sym_enum_type] = sym_enum_type,
  [sym_emits_entry] = sym_emits_entry,
  [sym_consumes_entry] = sym_consumes_entry,
  [sym_impl_entry] = sym_impl_entry,
  [sym_method] = sym_method,
  [sym_fragment_language] = sym_fragment_language,
  [sym_fragment] = sym_fragment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_service_repeat1] = aux_sym_service_repeat1,
  [aux_sym_db_entry_repeat1] = aux_sym_db_entry_repeat1,
  [aux_sym_table_repeat1] = aux_sym_table_repeat1,
  [aux_sym_enum_type_repeat1] = aux_sym_enum_type_repeat1,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_system] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_service] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lang] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_port] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_db] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_table] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_pk] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_emits] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_consumes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_impl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2196] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2197] = {
    .visible = true,
    .named = false,
  },
  [sym_fragment_text] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_system] = {
    .visible = true,
    .named = true,
  },
  [sym_service] = {
    .visible = true,
    .named = true,
  },
  [sym__entry] = {
    .visible = false,
    .named = true,
  },
  [sym_lang_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_port_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_db_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_table] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_type] = {
    .visible = true,
    .named = true,
  },
  [sym_emits_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_consumes_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_impl_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment_language] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_service_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_db_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_engine = 2,
  field_event = 3,
  field_language = 4,
  field_method = 5,
  field_name = 6,
  field_path = 7,
  field_type = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_engine] = "engine",
  [field_event] = "event",
  [field_language] = "language",
  [field_method] = "method",
  [field_name] = "name",
  [field_path] = "path",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 3},
  [6] = {.index = 7, .length = 4},
  [7] = {.index = 11, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_value, 1},
  [2] =
    {field_event, 1},
  [3] =
    {field_engine, 1},
  [4] =
    {field_body, 3},
    {field_method, 1},
    {field_path, 2},
  [7] =
    {field_body, 4},
    {field_language, 3},
    {field_method, 1},
    {field_path, 2},
  [11] =
    {field_name, 0},
    {field_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 18,
  [23] = 19,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 12,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 14,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      ADVANCE_MAP(
        '#', 16,
        '(', 7,
        ')', 8,
        ',', 5,
        '/', 13,
        ':', 6,
        '{', 3,
        '}', 4,
        0x2196, 9,
        0x2197, 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == 0x2196) ADVANCE(9);
      if (lookahead == 0x2197) ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_u2196);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_u2197);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_fragment_text);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == 0x2196) ADVANCE(9);
      if (lookahead == 0x2197) ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_fragment_text);
      if (lookahead != 0 &&
          lookahead != 0x2196 &&
          lookahead != 0x2197) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 0x2196 ||
          lookahead == 0x2197) ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'c', 1,
        'd', 2,
        'e', 3,
        'i', 4,
        'l', 5,
        'p', 6,
        's', 7,
        't', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'b') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'm') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'k') ADVANCE(15);
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == 'y') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_db);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_pk);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'b') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 'g') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 26:
      if (lookahead == 'v') ADVANCE(35);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_impl);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_lang);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_port);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 38:
      if (lookahead == 'm') ADVANCE(43);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_emits);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(44);
      END_STATE();
    case 41:
      if (lookahead == 'm') ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_table);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_system);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_service);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_consumes);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_system] = ACTIONS(1),
    [anon_sym_service] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_lang] = ACTIONS(1),
    [anon_sym_port] = ACTIONS(1),
    [anon_sym_db] = ACTIONS(1),
    [anon_sym_table] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_pk] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_emits] = ACTIONS(1),
    [anon_sym_consumes] = ACTIONS(1),
    [anon_sym_impl] = ACTIONS(1),
    [anon_sym_u2196] = ACTIONS(1),
    [anon_sym_u2197] = ACTIONS(1),
    [sym_path] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(72),
    [sym_system] = STATE(25),
    [anon_sym_system] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 1,
      anon_sym_lang,
    ACTIONS(11), 1,
      anon_sym_port,
    ACTIONS(13), 1,
      anon_sym_db,
    ACTIONS(15), 1,
      anon_sym_emits,
    ACTIONS(17), 1,
      anon_sym_consumes,
    ACTIONS(19), 1,
      anon_sym_impl,
    STATE(3), 8,
      sym__entry,
      sym_lang_entry,
      sym_port_entry,
      sym_db_entry,
      sym_emits_entry,
      sym_consumes_entry,
      sym_impl_entry,
      aux_sym_service_repeat1,
  [35] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_lang,
    ACTIONS(11), 1,
      anon_sym_port,
    ACTIONS(13), 1,
      anon_sym_db,
    ACTIONS(15), 1,
      anon_sym_emits,
    ACTIONS(17), 1,
      anon_sym_consumes,
    ACTIONS(19), 1,
      anon_sym_impl,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    STATE(4), 8,
      sym__entry,
      sym_lang_entry,
      sym_port_entry,
      sym_db_entry,
      sym_emits_entry,
      sym_consumes_entry,
      sym_impl_entry,
      aux_sym_service_repeat1,
  [70] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(25), 1,
      anon_sym_lang,
    ACTIONS(28), 1,
      anon_sym_port,
    ACTIONS(31), 1,
      anon_sym_db,
    ACTIONS(34), 1,
      anon_sym_emits,
    ACTIONS(37), 1,
      anon_sym_consumes,
    ACTIONS(40), 1,
      anon_sym_impl,
    STATE(4), 8,
      sym__entry,
      sym_lang_entry,
      sym_port_entry,
      sym_db_entry,
      sym_emits_entry,
      sym_consumes_entry,
      sym_impl_entry,
      aux_sym_service_repeat1,
  [105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [118] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [131] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [144] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [157] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [170] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [183] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [196] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [209] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [222] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [235] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [248] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 7,
      anon_sym_RBRACE,
      anon_sym_lang,
      anon_sym_port,
      anon_sym_db,
      anon_sym_emits,
      anon_sym_consumes,
      anon_sym_impl,
  [274] = 5,
    ACTIONS(69), 1,
      anon_sym_u2196,
    ACTIONS(71), 1,
      anon_sym_u2197,
    ACTIONS(73), 1,
      sym_fragment_text,
    ACTIONS(75), 1,
      sym_comment,
    STATE(19), 2,
      sym_fragment,
      aux_sym_fragment_repeat1,
  [291] = 5,
    ACTIONS(69), 1,
      anon_sym_u2196,
    ACTIONS(75), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_u2197,
    ACTIONS(79), 1,
      sym_fragment_text,
    STATE(21), 2,
      sym_fragment,
      aux_sym_fragment_repeat1,
  [308] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_enum,
    STATE(38), 3,
      sym__type,
      sym_type_name,
      sym_enum_type,
  [323] = 5,
    ACTIONS(75), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_u2196,
    ACTIONS(88), 1,
      anon_sym_u2197,
    ACTIONS(90), 1,
      sym_fragment_text,
    STATE(21), 2,
      sym_fragment,
      aux_sym_fragment_repeat1,
  [340] = 5,
    ACTIONS(69), 1,
      anon_sym_u2196,
    ACTIONS(75), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_u2197,
    ACTIONS(95), 1,
      sym_fragment_text,
    STATE(23), 2,
      sym_fragment,
      aux_sym_fragment_repeat1,
  [357] = 5,
    ACTIONS(69), 1,
      anon_sym_u2196,
    ACTIONS(75), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym_fragment_text,
    ACTIONS(97), 1,
      anon_sym_u2197,
    STATE(21), 2,
      sym_fragment,
      aux_sym_fragment_repeat1,
  [374] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      anon_sym_service,
    STATE(28), 2,
      sym_service,
      aux_sym_source_file_repeat1,
  [388] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_service,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    STATE(24), 2,
      sym_service,
      aux_sym_source_file_repeat1,
  [402] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    ACTIONS(107), 1,
      anon_sym_table,
    STATE(29), 2,
      sym_table,
      aux_sym_db_entry_repeat1,
  [416] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(111), 1,
      anon_sym_u2196,
    STATE(10), 1,
      sym_fragment,
    STATE(53), 1,
      sym_fragment_language,
  [432] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(115), 1,
      anon_sym_service,
    STATE(28), 2,
      sym_service,
      aux_sym_source_file_repeat1,
  [446] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_table,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    STATE(30), 2,
      sym_table,
      aux_sym_db_entry_repeat1,
  [460] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    ACTIONS(122), 1,
      anon_sym_table,
    STATE(30), 2,
      sym_table,
      aux_sym_db_entry_repeat1,
  [474] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_pk,
  [483] = 2,
    ACTIONS(75), 1,
      sym_comment,
    ACTIONS(127), 3,
      anon_sym_u2196,
      anon_sym_u2197,
      sym_fragment_text,
  [492] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    STATE(36), 1,
      aux_sym_table_repeat1,
  [505] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      sym_field,
  [518] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym_field,
  [531] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_table_repeat1,
  [544] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      sym_field,
  [557] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_pk,
    ACTIONS(143), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [568] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym_field,
  [581] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_table_repeat1,
  [594] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      aux_sym_table_repeat1,
  [607] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(158), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym_field,
  [620] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_RBRACE,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_table_repeat1,
  [633] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_enum_type_repeat1,
  [646] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(166), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym_field,
  [659] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_pk,
  [668] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_enum_type_repeat1,
  [681] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_pk,
  [690] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_COMMA,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_enum_type_repeat1,
  [703] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_pk,
  [712] = 2,
    ACTIONS(75), 1,
      sym_comment,
    ACTIONS(183), 3,
      anon_sym_u2196,
      anon_sym_u2197,
      sym_fragment_text,
  [721] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [729] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_u2196,
    STATE(15), 1,
      sym_fragment,
  [739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 2,
      ts_builtin_sym_end,
      anon_sym_service,
  [747] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 2,
      ts_builtin_sym_end,
      anon_sym_service,
  [755] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 2,
      anon_sym_RBRACE,
      anon_sym_table,
  [763] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [771] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_identifier,
    STATE(52), 1,
      sym_field,
  [781] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 2,
      anon_sym_RBRACE,
      anon_sym_table,
  [789] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 2,
      anon_sym_RBRACE,
      anon_sym_table,
  [797] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    ACTIONS(197), 1,
      sym_identifier,
  [807] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 2,
      ts_builtin_sym_end,
      anon_sym_service,
  [815] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 2,
      anon_sym_RBRACE,
      anon_sym_table,
  [823] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_identifier,
    STATE(84), 1,
      sym_method,
  [833] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [841] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
  [851] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym_identifier,
  [858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_COLON,
  [865] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
  [872] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym_identifier,
  [879] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      sym_identifier,
  [886] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      ts_builtin_sym_end,
  [893] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_number,
  [900] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      sym_identifier,
  [907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_identifier,
  [914] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
  [921] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_LBRACE,
  [928] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_identifier,
  [935] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LBRACE,
  [942] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym_identifier,
  [949] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_u2196,
  [956] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
  [963] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_LPAREN,
  [970] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_path,
  [977] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identifier,
  [984] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_path,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 105,
  [SMALL_STATE(6)] = 118,
  [SMALL_STATE(7)] = 131,
  [SMALL_STATE(8)] = 144,
  [SMALL_STATE(9)] = 157,
  [SMALL_STATE(10)] = 170,
  [SMALL_STATE(11)] = 183,
  [SMALL_STATE(12)] = 196,
  [SMALL_STATE(13)] = 209,
  [SMALL_STATE(14)] = 222,
  [SMALL_STATE(15)] = 235,
  [SMALL_STATE(16)] = 248,
  [SMALL_STATE(17)] = 261,
  [SMALL_STATE(18)] = 274,
  [SMALL_STATE(19)] = 291,
  [SMALL_STATE(20)] = 308,
  [SMALL_STATE(21)] = 323,
  [SMALL_STATE(22)] = 340,
  [SMALL_STATE(23)] = 357,
  [SMALL_STATE(24)] = 374,
  [SMALL_STATE(25)] = 388,
  [SMALL_STATE(26)] = 402,
  [SMALL_STATE(27)] = 416,
  [SMALL_STATE(28)] = 432,
  [SMALL_STATE(29)] = 446,
  [SMALL_STATE(30)] = 460,
  [SMALL_STATE(31)] = 474,
  [SMALL_STATE(32)] = 483,
  [SMALL_STATE(33)] = 492,
  [SMALL_STATE(34)] = 505,
  [SMALL_STATE(35)] = 518,
  [SMALL_STATE(36)] = 531,
  [SMALL_STATE(37)] = 544,
  [SMALL_STATE(38)] = 557,
  [SMALL_STATE(39)] = 568,
  [SMALL_STATE(40)] = 581,
  [SMALL_STATE(41)] = 594,
  [SMALL_STATE(42)] = 607,
  [SMALL_STATE(43)] = 620,
  [SMALL_STATE(44)] = 633,
  [SMALL_STATE(45)] = 646,
  [SMALL_STATE(46)] = 659,
  [SMALL_STATE(47)] = 668,
  [SMALL_STATE(48)] = 681,
  [SMALL_STATE(49)] = 690,
  [SMALL_STATE(50)] = 703,
  [SMALL_STATE(51)] = 712,
  [SMALL_STATE(52)] = 721,
  [SMALL_STATE(53)] = 729,
  [SMALL_STATE(54)] = 739,
  [SMALL_STATE(55)] = 747,
  [SMALL_STATE(56)] = 755,
  [SMALL_STATE(57)] = 763,
  [SMALL_STATE(58)] = 771,
  [SMALL_STATE(59)] = 781,
  [SMALL_STATE(60)] = 789,
  [SMALL_STATE(61)] = 797,
  [SMALL_STATE(62)] = 807,
  [SMALL_STATE(63)] = 815,
  [SMALL_STATE(64)] = 823,
  [SMALL_STATE(65)] = 833,
  [SMALL_STATE(66)] = 841,
  [SMALL_STATE(67)] = 851,
  [SMALL_STATE(68)] = 858,
  [SMALL_STATE(69)] = 865,
  [SMALL_STATE(70)] = 872,
  [SMALL_STATE(71)] = 879,
  [SMALL_STATE(72)] = 886,
  [SMALL_STATE(73)] = 893,
  [SMALL_STATE(74)] = 900,
  [SMALL_STATE(75)] = 907,
  [SMALL_STATE(76)] = 914,
  [SMALL_STATE(77)] = 921,
  [SMALL_STATE(78)] = 928,
  [SMALL_STATE(79)] = 935,
  [SMALL_STATE(80)] = 942,
  [SMALL_STATE(81)] = 949,
  [SMALL_STATE(82)] = 956,
  [SMALL_STATE(83)] = 963,
  [SMALL_STATE(84)] = 970,
  [SMALL_STATE(85)] = 977,
  [SMALL_STATE(86)] = 984,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lang_entry, 2, 0, 2),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_consumes_entry, 2, 0, 3),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_entry, 2, 0, 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_db_entry, 4, 0, 4),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_emits_entry, 4, 0, 3),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_impl_entry, 4, 0, 5),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_db_entry, 5, 0, 4),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_emits_entry, 5, 0, 3),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_impl_entry, 5, 0, 6),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_emits_entry, 6, 0, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_emits_entry, 7, 0, 3),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_db_entry_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_db_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fragment, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 7),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_type, 4, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_type, 5, 0, 0),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_type_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_type_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_type, 6, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fragment, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system, 2, 0, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 5, 0, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 4, 0, 1),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 7),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 5, 0, 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 6, 0, 1),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service, 4, 0, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 7, 0, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [217] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment_language, 1, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_arch(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "arch",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
